Add BIP350 Bech32m support
bitcoinjs/bech32 pull request #40
Opened 2021-02-12 17:41 UTC by andrewtoth

This PR adds support for BIP350 bech32m encoding. The relevant test vectors are included from [here](https://github.com/bitcoin/bips/blob/master/bip-0350.mediawiki#Test_vectors_for_Bech32m).

Note this is a backwards incompatible change. A new `encoding` argument is required when encoding or decoding.

2021-02-13 01:13 UTC, junderw requested changes
LGTM as far as code is concerned. However, this change is about 99.9% just a question of "how do we want to change the API to accommodate for this?"

I made some comments to that effect.

Please let me know what you think.

2021-02-13 01:13 UTC, junderw commented on index.js
> +function encode (prefix, words, encoding, LIMIT) {
Handling of invalid encoding.

2021-02-13 01:13 UTC, junderw commented on index.js
> +  encodings: encodings
What about splitting the namespace into two?

ie.
```
module.exports = {
  bech32: {
    decodeUnsafe: setEncoding(decodeUnsafe, 'bech32'),
    ...
  },
  bech32m: {
    decodeUnsafe: setEncoding(decodeUnsafe, 'bech32m'),
    ...
  },
}
```

2021-02-13 19:17 UTC, andrewtoth commented on index.js
> +  encodings: encodings
Thank you for the quick review! Initially I liked this, but now I'm thinking it might make it a bit awkward for `toWords/fromWords`. 
It could be used like:
```
const { bech32, bech32m } = require('bech32')
const decoded = bech32.decode(addr) || bech32m.decode(addr)
```
which is great. But if say right now it's used as:
```
const bech32 = require('bech32')
const words = bech32.encode(prefix, bech32.toWords(data))
```
Now this will change to:
```
const bech32 = require('bech32')
const addr = bech32.bech32.encode(prefix, bech32.toWords(data))
```
If that's a common pattern of usage then I think it would be cleaner to just add the `encoding` parameter into the `encode/decode` methods. Otherwise `toWords/fromWords` would also have to be deconstructed like `const { bech32, toWords } = require('bech32')` and that would cause a lot bigger diff in libraries trying to upgrade cleanly. But, I'm not super opinionated here and will defer to whatever will get this merged without too much bikeshedding.

2021-02-14 03:18 UTC, junderw approved these changes
I will be willing to merge this with my modifications.

Please let me know if you approve and I'll merge it.

2021-02-14 15:05 UTC, andrewtoth commented
ACK - LGTM, thanks!
Github won't actually let me approve through the review process since I'm the PR author.

2021-02-14 23:35 UTC, merged